<script lang="ts">
	import { onMount } from 'svelte';
	import { CORE_COMMODITIES } from '$lib/commodities.js';
	import { computeCommodityAmount } from '$lib/prices.js';
	import type { PriceData, DayPrices } from '$lib/prices.js';
	import {
		btcAmount,
		selectedDate,
		activePreset,
		scrollToCommodity,
		setBtcFromSlider,
		setDateFromPicker,
		activatePreset,
		hydrateFromUrl,
	} from '$lib/stores/url.js';
	import { formatBtc } from '$lib/format.js';
	import { parseAmountInput } from '$lib/amount-input.js';
	import { applyDetent, DETENT_BTC_VALUES } from '$lib/detent.js';
	import { getEntity } from '$lib/holdings.js';
	import { createKonamiTracker } from '$lib/konami.js';
	import {
		playbackDurationMs,
		playbackIndexAt,
		milestonesCrossed,
		type Milestone,
	} from '$lib/playback.js';
	import HeroStage from '$lib/components/HeroStage.svelte';
	import PresetBar from '$lib/components/PresetBar.svelte';
	import NetworkWeightPanel from '$lib/components/NetworkWeightPanel.svelte';
	import {
		organizationJsonLd,
		websiteJsonLd,
		webPageJsonLd,
		faqJsonLd,
		breadcrumbJsonLd,
	} from '$lib/seo/jsonld.js';
	import { HOMEPAGE_FAQS } from '$lib/seo/faqs.js';

	let { data } = $props();

	// Initial prices are the latest day only (inlined via +page.ts → load
	// → prices-latest.json). The full archive lazy-loads in onMount. The
	// first commodity (gold) renders eagerly so its Shiba ships in the
	// prerendered HTML and anchors LCP; the other 7 sections lazy-mount
	// via IntersectionObserver to keep hydration cheap.
	let prices = $state<PriceData>(data.initialPrices);
	let firstDate = $state(data.firstDate);
	let lastDate = $state(data.lastDate);

	// Dataset-derived milestone markers (delight brief §1.4c) — fetched
	// alongside the full archive in onMount, same lazy-load shape as
	// prices.json. Generated by scripts/build-milestones.ts; never hand-edited.
	let milestones = $state<Milestone[]>([]);

	// Seed selectedDate before the first reactive read so the inlined day's
	// data resolves. URL params are applied in onMount once the full archive
	// is loaded — applying them earlier would cause a hydration mismatch
	// when the URL date isn't in the inlined day.
	selectedDate.set(data.lastDate);

	function getDayPrices(date: string): DayPrices | undefined {
		return prices?.[date];
	}

	// ── Slider log-scale helpers ────────────────────────────────
	const BTC_MIN = 0.00000001; // 1 sat
	const BTC_MAX = 21_000_000;
	const LOG_MIN = Math.log10(BTC_MIN);
	const LOG_MAX = Math.log10(BTC_MAX);
	const SLIDER_STEPS = 10000;

	function btcToSlider(btc: number): number {
		const clamped = Math.max(BTC_MIN, Math.min(BTC_MAX, btc));
		const log = Math.log10(clamped);
		return Math.round(((log - LOG_MIN) / (LOG_MAX - LOG_MIN)) * SLIDER_STEPS);
	}

	function sliderToBtc(pos: number): number {
		const log = LOG_MIN + (pos / SLIDER_STEPS) * (LOG_MAX - LOG_MIN);
		const raw = Math.pow(10, log);
		if (raw >= 1000) return Math.round(raw);
		if (raw >= 1) return Math.round(raw * 100) / 100;
		if (raw >= 0.001) return Math.round(raw * 10000) / 10000;
		if (raw >= 0.00001) return Math.round(raw * 100000000) / 100000000;
		return Math.round(raw * 100000000) / 100000000;
	}

	// Dual-mode slider: 'btc' adjusts BTC amount; 'date' locks BTC and scrubs through history.
	let sliderMode = $state<'btc' | 'date'>('btc');
	let lockedBtcForDateMode = $state(1);

	const sortedDates = $derived(prices ? Object.keys(prices).sort() : []);

	function dateToSliderIdx(date: string, dates: string[]): number {
		if (!dates.length) return SLIDER_STEPS;
		let idx = dates.indexOf(date);
		if (idx === -1) {
			idx = dates.findIndex(d => d >= date);
			if (idx === -1) idx = dates.length - 1;
		}
		return Math.round((idx / Math.max(1, dates.length - 1)) * SLIDER_STEPS);
	}

	function sliderIdxToDate(pos: number, dates: string[]): string {
		if (!dates.length) return '';
		const idx = Math.round((pos / SLIDER_STEPS) * (dates.length - 1));
		return dates[Math.max(0, Math.min(dates.length - 1, idx))];
	}

	let sliderPos = $state(btcToSlider(1));

	// ── Scene BTC + preset tween ────────────────────────────────
	// `sceneBtc` is the value the hero stage, hero readout, and slider display
	// follow. Normally it mirrors the committed store value ($btcAmount). On a
	// preset click it is TWEENED (≈600 ms, log-eased) from the current value to
	// the preset's so the camera dollies the move and the slider visibly travels
	// — pre-launch review §1's "missed trick". The committed $btcAmount / URL /
	// preset slug are set immediately by activatePreset (URL contract untouched);
	// the tween is a visual animation on top, never written to the URL.
	let sceneBtc = $state(1);
	let tweening = $state(false);
	let tweenRaf = 0;
	let reduceMotion = $state(false);

	function cancelTween() {
		if (tweenRaf) cancelAnimationFrame(tweenRaf);
		tweenRaf = 0;
		tweening = false;
	}

	function tweenSceneBtc(from: number, to: number, ms: number) {
		cancelTween();
		tweening = true;
		const t0 = performance.now();
		const logFrom = Math.log10(Math.max(from, BTC_MIN));
		const logTo = Math.log10(Math.max(to, BTC_MIN));
		const step = (now: number) => {
			const k = Math.min((now - t0) / ms, 1);
			const eased = k < 0.5 ? 2 * k * k : 1 - (-2 * k + 2) ** 2 / 2; // easeInOutQuad
			sceneBtc = 10 ** (logFrom + (logTo - logFrom) * eased);
			sliderPos = btcToSlider(sceneBtc); // slider travels with the tween (log → linear)
			if (k < 1) {
				tweenRaf = requestAnimationFrame(step);
			} else {
				sceneBtc = to;
				sliderPos = btcToSlider(to);
				cancelTween();
			}
		};
		tweenRaf = requestAnimationFrame(step);
	}

	$effect(() => {
		// Mirror the committed store to the scene/slider, EXCEPT while a preset
		// tween owns those values.
		if (tweening) return;
		sceneBtc = $btcAmount;
		if (sliderMode === 'btc') {
			const newPos = btcToSlider($btcAmount);
			if (Math.abs(newPos - sliderPos) > 1) sliderPos = newPos;
		} else {
			const newPos = dateToSliderIdx($selectedDate, sortedDates);
			if (Math.abs(newPos - sliderPos) > 1) sliderPos = newPos;
		}
	});

	// ── Detents (delight brief §1.5b) ───────────────────────────
	// Magnetic snap in slider space at the meaningful BTC values. Positions
	// derive from the same btcToSlider as everything else — no duplicate log
	// maths. `navigator.vibrate` ticks once per snap ENGAGEMENT (unsnapped →
	// snapped), feature-detected, and skipped under reduced-motion.
	const detentPositions = DETENT_BTC_VALUES.map(btcToSlider);
	let snappedDetent: number | null = null;

	function handleSliderInput(e: Event) {
		cancelTween(); // a manual drag interrupts any preset tween
		stopPlayback(); // ...and any running date playback (brief §1.4a)
		const target = e.target as HTMLInputElement;
		const rawPos = parseInt(target.value);
		if (sliderMode === 'btc') {
			const snapped = applyDetent(rawPos, detentPositions);
			if (snapped !== rawPos && snappedDetent !== snapped) {
				snappedDetent = snapped;
				if (!reduceMotion) navigator.vibrate?.(10);
			} else if (snapped === rawPos) {
				snappedDetent = null;
			}
			sliderPos = snapped;
			target.value = String(snapped); // keep the native thumb on the detent
			setBtcFromSlider(sliderToBtc(snapped));
		} else {
			sliderPos = rawPos;
			setDateFromPicker(sliderIdxToDate(rawPos, sortedDates));
		}
	}

	// Mode switching — one implementation shared by the dblclick shortcut, the
	// visible BTC|DATE segmented control, and the `t` key (brief §1.5c).
	function setSliderMode(mode: 'btc' | 'date') {
		if (mode === sliderMode) return;
		stopPlayback(); // any mode switch stops date playback (brief §1.4a)
		if (mode === 'date') {
			if (sortedDates.length <= 1) return; // archive not loaded yet
			lockedBtcForDateMode = $btcAmount;
			// Baseline the crossing-detection cursor to the date we're entering
			// on, so the first scrub/play tick afterwards is compared against
			// where we actually started, not a stale value from the last time
			// date mode was active (which could read as a spurious big jump).
			lastDateForCrossing = $selectedDate;
			sliderMode = 'date';
		} else {
			sliderMode = 'btc';
			setBtcFromSlider(lockedBtcForDateMode);
		}
	}

	function handleSliderDblClick() {
		setSliderMode(sliderMode === 'btc' ? 'date' : 'btc');
	}

	// ── Play button (delight brief §1.4a) ───────────────────────
	// Sweeps `selectedDate` across the sorted date array on an eased pace
	// (pure maths in src/lib/playback.ts), driven by requestAnimationFrame —
	// never setInterval. Every tick commits through `setDateFromPicker`, the
	// SAME path the slider drag and the year-jump keys use, so URL state
	// stays canonical regardless of the trigger.
	//
	// stores/url.ts debounces `history.replaceState` at 100 ms and RESETS
	// that timer on every store write (see `pushToUrl`). Since playback keeps
	// committing a new date roughly every animation frame while it's moving
	// fast (well under the 100 ms debounce window), the URL write is deferred
	// for the entire moving portion of the sweep and only actually fires once
	// playback pauses, ends, or slows enough near the eased edges to leave a
	// >100 ms gap between commits — i.e. one or two `replaceState` calls for
	// a 12 s sweep, not one per tick. Confirmed by reading stores/url.ts.
	let playing = $state(false);
	let playRaf = 0;
	let playStartTime = 0;
	let playStartIdx = 0;
	let playDurationMs = 0;

	/** Index of `date` in the sorted array, falling back to the nearest later
	 *  date (same fallback shape as `dateToSliderIdx`, but returning a raw
	 *  array index rather than a slider position). */
	function dateArrayIndex(date: string, dates: string[]): number {
		let idx = dates.indexOf(date);
		if (idx === -1) {
			idx = dates.findIndex((d) => d >= date);
			if (idx === -1) idx = dates.length - 1;
		}
		return idx;
	}

	function stopPlayback() {
		if (playRaf) cancelAnimationFrame(playRaf);
		playRaf = 0;
		playing = false;
	}

	function startPlayback() {
		if (sliderMode !== 'date' || reduceMotion || sortedDates.length < 2) return;
		const startIdx = dateArrayIndex($selectedDate, sortedDates);
		const endIdx = sortedDates.length - 1;
		if (startIdx >= endIdx) return; // already at the latest date — nothing to play
		cancelTween(); // playback (date) and the preset tween (BTC) never run together
		playStartIdx = startIdx;
		playDurationMs = playbackDurationMs(sortedDates.length, startIdx);
		playStartTime = performance.now();
		playing = true;

		const step = (now: number) => {
			const elapsed = now - playStartTime;
			const idx = playbackIndexAt(elapsed, playDurationMs, sortedDates.length, playStartIdx);
			const date = sortedDates[idx];
			if (date !== $selectedDate) setDateFromPicker(date);
			if (idx >= endIdx) {
				stopPlayback(); // reached the end — stop, stay on the latest date, no loop
				return;
			}
			playRaf = requestAnimationFrame(step);
		};
		playRaf = requestAnimationFrame(step);
	}

	function togglePlayback() {
		if (playing) stopPlayback();
		else startPlayback();
	}

	// ── Milestone markers + crossing caption (delight brief §1.4c) ───────
	// Dots render on the date-mode slider track at each dataset-derived
	// milestone (static/milestones.json — see scripts/build-milestones.ts;
	// never hand-edited). Whenever the viewed date crosses one — via
	// playback OR manual scrubbing, from either side — its label appears as
	// a transient caption for ~2.5 s, then disappears.
	//
	// Choice made (brief offered transient-fade vs. persistent-within-±3-days
	// and asked to document): transient-on-crossing. Reads better under
	// playback, where several milestones can sweep by in one 12 s run — a
	// persistent "am I still within 3 days of the last one" caption would
	// either linger stale or double up as the next one arrives, while a
	// transient caption reads as a ticker of what was just passed. Under
	// reduced motion the caption still appears/disappears on the same
	// schedule, just without the CSS fade (see .milestone-caption below).
	// Plain (non-rune) bookkeeping variable, deliberately NOT $state: the
	// $effect below both reads and writes it, and making it reactive state
	// would make the effect depend on its own write, self-triggering a
	// second run on every tick. Under two selectedDate changes arriving
	// close together (e.g. two rapid scrubs) that self-triggered rerun can
	// still be in flight when the next external change lands, so the
	// second crossing check reads a stale `prev` — observed live as a
	// dropped caption when driving the page with Playwright. A plain
	// variable is invisible to Svelte's dependency tracking, so the effect
	// only re-runs on genuine sliderMode/selectedDate changes.
	let lastDateForCrossing = '';
	let milestoneCaption = $state<Milestone | null>(null);
	let milestoneCaptionTimer: ReturnType<typeof setTimeout> | undefined;
	const MILESTONE_CAPTION_MS = 2500;

	function showMilestoneCaption(m: Milestone) {
		milestoneCaption = m;
		if (milestoneCaptionTimer) clearTimeout(milestoneCaptionTimer);
		milestoneCaptionTimer = setTimeout(() => {
			milestoneCaption = null;
		}, MILESTONE_CAPTION_MS);
	}

	$effect(() => {
		if (sliderMode !== 'date' || !$selectedDate) return;
		const prev = lastDateForCrossing;
		lastDateForCrossing = $selectedDate;
		if (!prev) return; // no prior date to compare (just entered date mode)
		const crossed = milestonesCrossed(prev, $selectedDate, milestones);
		if (crossed.length) showMilestoneCaption(crossed[crossed.length - 1]);
	});

	const milestoneMarks = $derived.by(() => {
		if (sliderMode !== 'date' || sortedDates.length < 2) return [];
		return milestones.map((m) => ({
			...m,
			pct: (dateToSliderIdx(m.date, sortedDates) / SLIDER_STEPS) * 100,
		}));
	});

	// ── Keyboard (delight brief §1.5c) ──────────────────────────
	// On the sliders: Shift+arrows / PageUp/Down jump a decade (BTC mode) or
	// one year (date mode). Native unmodified arrows keep their built-in nudge.
	function handleSliderKeydown(e: KeyboardEvent) {
		const isJumpKey =
			e.key === 'PageUp' ||
			e.key === 'PageDown' ||
			(e.shiftKey && (e.key === 'ArrowRight' || e.key === 'ArrowLeft' || e.key === 'ArrowUp' || e.key === 'ArrowDown'));
		if (!isJumpKey) return;
		e.preventDefault();
		const up = e.key === 'PageUp' || e.key === 'ArrowRight' || e.key === 'ArrowUp';
		cancelTween();
		stopPlayback(); // a date jump key interrupts any running playback
		if (sliderMode === 'btc') {
			const next = Math.min(BTC_MAX, Math.max(BTC_MIN, $btcAmount * (up ? 10 : 0.1)));
			setBtcFromSlider(next);
		} else if (sortedDates.length > 1 && $selectedDate) {
			const targetYear = Number($selectedDate.slice(0, 4)) + (up ? 1 : -1);
			const target = `${targetYear}${$selectedDate.slice(4)}`;
			setDateFromPicker(sliderIdxToDate(dateToSliderIdx(target, sortedDates), sortedDates));
		}
	}

	// Konami code (delight brief §2.4): ↑↑↓↓←→←→BA anywhere on the page
	// triggers Sat's three easter-egg tricks in sequence. Tracker is a pure
	// state machine (src/lib/konami.ts); the DOM/reduced-motion/mixer guards
	// all live in LiveStage's `triggerKonami`, reached through HeroStage's
	// thin forwarding export.
	const konamiTracker = createKonamiTracker();
	let heroStageEl: HeroStage | undefined = $state();

	// Global keys: g/s/p/c switch hero tabs, t toggles BTC/date mode, space
	// toggles date playback, and the Konami code triggers the dog's tricks.
	// Only when nothing focusable owns the keystroke and no ctrl/alt/meta
	// chord — same guard for all of them.
	function handleGlobalKeydown(e: KeyboardEvent) {
		if (e.ctrlKey || e.metaKey || e.altKey) return;
		const t = e.target as HTMLElement | null;
		if (t && (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.tagName === 'SELECT' || t.isContentEditable))
			return;

		// Space bar: play/pause (brief §1.4a), date mode only, and only where
		// the ▶ button itself would be shown (hidden under reduced motion).
		// preventDefault so space doesn't also scroll the page.
		if (e.key === ' ' && sliderMode === 'date' && !reduceMotion) {
			e.preventDefault();
			togglePlayback();
			return;
		}

		if (konamiTracker.feed(e.key) === 'matched') {
			heroStageEl?.triggerKonami();
		}

		const key = e.key.toLowerCase();
		const tabByKey: Record<string, string> = { g: 'gold', s: 'silver', p: 'pu238', c: 'cocaine' };
		if (key in tabByKey) {
			selectedCommodity = tabByKey[key];
		} else if (key === 't') {
			setSliderMode(sliderMode === 'btc' ? 'date' : 'btc');
		}
	}

	// ── Click-to-type amount (delight brief §1.5a) ──────────────
	// The big BTC readout becomes an input on click (BTC mode only). Enter
	// commits through the same setter as the slider; Escape reverts; blur
	// commits if the draft parses, otherwise reverts silently — invalid input
	// has no error state, it simply doesn't commit.
	let editingAmount = $state(false);
	let amountDraft = $state('');
	let amountInputEl: HTMLInputElement | undefined = $state();

	function startAmountEdit() {
		if (sliderMode !== 'btc' || tweening) return;
		amountDraft = formatBtc(sceneBtc).replace(/ BTC$/, '');
		editingAmount = true;
		queueMicrotask(() => amountInputEl?.select());
	}

	function commitAmountEdit() {
		const parsed = parseAmountInput(amountDraft, dayPrices?.btc ?? null);
		editingAmount = false;
		if (parsed === null) return; // revert: readout re-renders from state
		cancelTween();
		stopPlayback(); // defensive — amount edit only reachable in btc mode anyway
		setBtcFromSlider(parsed);
	}

	function handleAmountKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter') {
			e.preventDefault();
			commitAmountEdit();
		} else if (e.key === 'Escape') {
			e.preventDefault();
			editingAmount = false; // cancel — no commit
		}
	}

	// Compact pinned bar — appears once the user has scrolled past the
	// full controls card. Sentinel sits just below the controls; we watch
	// its IntersectionObserver entry and flip the bar visible when it
	// has scrolled above the viewport (not just merely off-screen below).
	let sentinelEl: HTMLElement | undefined = $state();
	let showStickyBar = $state(false);

	$effect(() => {
		if (!sentinelEl) return;
		const obs = new IntersectionObserver((entries) => {
			for (const entry of entries) {
				if (entry.isIntersecting) {
					showStickyBar = false;
				} else {
					// Off-screen — distinguish above (scrolled past) from below (not yet reached).
					showStickyBar = entry.boundingClientRect.top < 0;
				}
			}
		});
		obs.observe(sentinelEl);
		return () => obs.disconnect();
	});

	function handlePresetSelect(slug: string) {
		stopPlayback(); // a preset click interrupts any running date playback
		sliderMode = 'btc';
		const entity = getEntity(slug);
		const from = sceneBtc;
		activatePreset(slug); // commits $btcAmount / date / preset slug + URL immediately
		// Play the size change as a camera move (reduced-motion → instant).
		if (entity && !reduceMotion) tweenSceneBtc(from, entity.btc, 600);
	}

	const dayPrices = $derived(getDayPrices($selectedDate));

	function formatUsd(value: number): string {
		if (value >= 1_000_000_000_000) {
			return '$' + (value / 1_000_000_000_000).toFixed(2) + 'T';
		}
		if (value >= 1_000_000_000) {
			return '$' + (value / 1_000_000_000).toFixed(2) + 'B';
		}
		if (value >= 1_000_000) {
			return '$' + (value / 1_000_000).toFixed(2) + 'M';
		}
		return '$' + value.toLocaleString('en-US', {
			minimumFractionDigits: 2,
			maximumFractionDigits: 2,
		});
	}

	function formatDateReadout(dateStr: string): string {
		if (!dateStr) return '';
		const d = new Date(dateStr + 'T00:00:00');
		return d.toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric',
		});
	}

	// One-stage layout: all four launch commodities are tabs on the single hero
	// stage — the three cube metals (gold, silver, pu238) share the live WebGL
	// stage; cocaine swaps it for the inline-SVG brick stack. Locked tab order
	// survives from CORE_COMMODITIES (pageOrder): gold, silver, pu238, cocaine.
	const HERO_COMMODITIES = CORE_COMMODITIES;

	// Active hero tab. Seeded from a ?commodity= deep-link (scrollToCommodity),
	// default gold; tab clicks update it locally (no URL write — contract intact).
	let selectedCommodity = $state('gold');
	$effect(() => {
		const c = $scrollToCommodity;
		if (c && HERO_COMMODITIES.some((m) => m.id === c)) selectedCommodity = c;
	});

	// Amounts feed every hero tab from the tweened sceneBtc so a preset move
	// animates everything together.
	const heroAmounts = $derived(
		Object.fromEntries(
			HERO_COMMODITIES.map((c) => [c.id, computeCommodityAmount(sceneBtc, c, dayPrices)])
		) as Record<string, number | null>
	);

	// ── Open Graph metadata (reactive) ──────────────────────────
	// og:image points at /og-image (functions/og-image.ts) so the share
	// preview reflects the current slider state. When ?commodity=X is set
	// (via deep-link or a per-panel share button), the title and image
	// pivot to that commodity; otherwise gold is the default voice.
	// Server-prerender bakes the defaults; client hydration updates the
	// reactive bindings for JS-aware crawlers.
	const ogCommodity = $derived(
		CORE_COMMODITIES.find((c) => c.id === $scrollToCommodity) ??
			CORE_COMMODITIES.find((c) => c.id === 'gold')
	);

	const ogReadoutText = $derived.by(() => {
		if (!ogCommodity || !dayPrices) return null;
		const amt = computeCommodityAmount($btcAmount, ogCommodity, dayPrices);
		if (amt === null || !isFinite(amt) || amt <= 0) return null;
		if (ogCommodity.unit === 'troy_oz') {
			const formatted =
				amt >= 1000 ? Math.round(amt).toLocaleString('en-US')
					: amt >= 1 ? amt.toFixed(2)
						: amt.toPrecision(3);
			return `${formatted} troy oz`;
		}
		// Grams-unit commodities use the consumer ladder (kg/tonnes at scale).
		if (ogCommodity.unit === 'gram' && ogCommodity.unitMassGrams) {
			// Inline grams formatter — mirrors functions/_lib.ts formatHeadlineAmount
			const g = amt * ogCommodity.unitMassGrams;
			if (g >= 1_000_000) return `${(g / 1_000_000).toFixed(2)} tonnes`;
			if (g >= 1000) return `${(g / 1000).toFixed(2)} kg`;
			if (g < 1) return `${(g * 1000).toFixed(0)} mg`;
			return `${g.toFixed(1)} g`;
		}
		return null;
	});

	const ogCommodityName = $derived(ogCommodity?.displayName.toLowerCase() ?? 'gold');

	// Page-level <title> stays keyword-stable so it doesn't churn with the
	// daily ratio (which used to bake into the title and tanked queries like
	// "bitcoin to gold" because the title kept shifting). og:title still
	// carries the dynamic ratio so share previews remain conversation-worthy.
	//
	// Query-first, brand as suffix: the highest-weight slot goes to the search
	// phrase, not to a brand nobody searches yet. Kept under 60 chars so it
	// doesn't truncate in SERPs. Only commodities with a live /btc/* page may
	// be named here — the previous title advertised oil, which 404s.
	const pageTitle = 'How Much Gold Does 1 BTC Buy? — Bitcoin Weigh-In';
	const pageDescription =
		"Bitcoin's purchasing power, visualised in physical commodities. See how much gold, silver, cash or plutonium one BTC buys, with a daily-updated dataset back to 2013.";

	const ogTitle = $derived(
		ogReadoutText
			? `${formatBtc($btcAmount)} = ${ogReadoutText} of ${ogCommodityName} · Bitcoin Weigh-In`
			: pageTitle
	);

	const ogDescription = $derived(
		ogReadoutText
			? `What does ${formatBtc($btcAmount)} buy? ${ogReadoutText} of ${ogCommodityName} today. Explore BTC purchasing power across gold, silver, plutonium-238 and more.`
			: pageDescription
	);

	// Default state (1 BTC, latest date, no preset/commodity) emits the
	// bare canonical and an undated og-image. The SSR pass seeds
	// selectedDate to the build day, which baked a dated og:url into the
	// prerendered HTML — fragmenting the share graph by day and dating
	// the share card for anyone sharing the bare homepage later (SEO
	// audit C2). Dynamic values still apply after user interaction.
	const isDefaultState = $derived(
		$btcAmount === 1 &&
			!$activePreset &&
			!$scrollToCommodity &&
			(!$selectedDate || $selectedDate === lastDate)
	);

	const ogPageUrl = $derived.by(() => {
		if (isDefaultState) return 'https://bitcoinweighin.com/';
		const params = new URLSearchParams();
		if ($btcAmount !== 1) params.set('btc', String($btcAmount));
		if ($selectedDate) params.set('date', $selectedDate);
		if ($activePreset) params.set('preset', $activePreset);
		if ($scrollToCommodity) params.set('commodity', $scrollToCommodity);
		const qs = params.toString();
		return `https://bitcoinweighin.com/${qs ? '?' + qs : ''}`;
	});

	const ogImageUrl = $derived.by(() => {
		if (isDefaultState) return 'https://bitcoinweighin.com/og-image?btc=1';
		const params = new URLSearchParams();
		params.set('btc', String($btcAmount));
		if ($selectedDate) params.set('date', $selectedDate);
		if ($scrollToCommodity) params.set('commodity', $scrollToCommodity);
		return `https://bitcoinweighin.com/og-image?${params.toString()}`;
	});

	const ogImageAlt = $derived(
		ogReadoutText
			? `${formatBtc($btcAmount)} buys ${ogReadoutText} of ${ogCommodityName}`
			: 'Bitcoin Weigh-In — BTC purchasing power in physical commodities'
	);

	// ── Beehiiv subscribe form ──────────────────────────────────
	// Beehiiv v3 INLINE forms render exactly where the embed <script> tag
	// sits in the DOM; only popup/slide/sticky layouts self-position. The
	// previous body-append + idle-defer put the form at the literal bottom
	// of the document, seconds late — invisible unless a visitor hard-
	// scrolled and waited, i.e. no signups. The script is now injected
	// INTO the visible subscribe section below, when that section
	// approaches the viewport (600 px root margin), with a timed floor so
	// a popup/slide-configured form still fires for non-scrollers.
	let subscribeSlotEl: HTMLElement | undefined = $state();

	$effect(() => {
		const slot = subscribeSlotEl;
		if (!slot) return;
		const BEEHIIV_ID = '6a25c97c-4b00-4c3e-9ed4-cb25c2db7be2';
		const inject = () => {
			if (document.querySelector(`script[data-beehiiv-form="${BEEHIIV_ID}"]`)) return;
			const s = document.createElement('script');
			s.async = true;
			s.src = 'https://subscribe-forms.beehiiv.com/v3/loader.js';
			s.setAttribute('data-beehiiv-form', BEEHIIV_ID);
			slot.appendChild(s);
		};
		const obs = new IntersectionObserver(
			(entries) => {
				if (entries.some((e) => e.isIntersecting)) {
					inject();
					obs.disconnect();
				}
			},
			{ rootMargin: '600px 0px' }
		);
		obs.observe(slot);
		const floor = setTimeout(inject, 8000);
		return () => {
			obs.disconnect();
			clearTimeout(floor);
		};
	});

	onMount(async () => {
		// Preset tween respects reduced-motion (jump instead of dolly).
		reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;

		// Background load of the full archive so the slider/preset can
		// reach historical dates. Initial render already has today's
		// prices inlined; this fills in the rest. Milestones.json is tiny
		// (a handful of rows) and fetched alongside it — simplest correct
		// thing per the delight brief, matching how the archive itself lazy-
		// loads rather than inlining via the page's load function.
		const [archiveRes, milestonesRes] = await Promise.all([
			fetch('/prices.json'),
			fetch('/milestones.json'),
		]);
		const archive: PriceData = await archiveRes.json();
		prices = archive;
		const dates = Object.keys(archive).sort();
		firstDate = dates[0];
		lastDate = dates[dates.length - 1];
		milestones = await milestonesRes.json();

		// URL params come in after the archive arrives so the requested date
		// is guaranteed to be in `prices`. A brief flicker on deep-links is
		// the cost of avoiding an SSR/client hydration mismatch.
		hydrateFromUrl(lastDate);
	});
</script>

<!-- Global keys (brief §1.5c): g/s/p/c switch hero tabs, t toggles BTC/date.
     Guarded inside the handler — never fires while an input owns focus. -->
<svelte:window onkeydown={handleGlobalKeydown} />

<svelte:head>
	<title>{pageTitle}</title>
	<meta name="description" content={pageDescription} />
	<link rel="canonical" href="https://bitcoinweighin.com/" />
	<!--
		header.webp is the confirmed LCP element (PageSpeed's LCP breakdown)
		but had no preload hint, so the browser couldn't discover/start
		fetching it until HTML parsing reached the <img> tag deep in the
		body — well after the head's own preloaded fonts + shiba sprite were
		already competing for bandwidth. Homepage-only (this file is the
		only place header.webp is used), so this lives here rather than in
		the shared app.html, which would waste the preload on every other
		route.
	-->
	<link
		rel="preload"
		as="image"
		href="/header.webp"
		imagesrcset="/header@1x.webp 1x, /header.webp 2x"
		fetchpriority="high"
	/>
	<!--
		Open Graph + Twitter cards. The og:image hits the /og-image Pages
		Function (functions/og-image.ts) with the current slider state, so
		share previews reflect the URL's btc / date / commodity params.
		Defaults bake into the prerendered HTML for non-JS crawlers; the
		reactive bindings update for JS-aware crawlers and post-hydration.
	-->
	<meta property="og:type" content="website" />
	<meta property="og:site_name" content="Bitcoin Weigh-In" />
	<meta property="og:title" content={ogTitle} />
	<meta property="og:description" content={ogDescription} />
	<meta property="og:url" content={ogPageUrl} />
	<meta property="og:image" content={ogImageUrl} />
	<meta property="og:image:width" content="1200" />
	<meta property="og:image:height" content="630" />
	<meta property="og:image:alt" content={ogImageAlt} />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content={ogTitle} />
	<meta name="twitter:description" content={ogDescription} />
	<meta name="twitter:image" content={ogImageUrl} />
	<!-- Structured data: WebSite + Organization + WebPage + FAQPage + BreadcrumbList. Stable across daily rebuilds so Google's structured-data cache stays warm. -->
	{@html `<script type="application/ld+json">${websiteJsonLd()}</script>`}
	{@html `<script type="application/ld+json">${organizationJsonLd()}</script>`}
	{@html `<script type="application/ld+json">${webPageJsonLd({ url: 'https://bitcoinweighin.com/', name: pageTitle, description: pageDescription })}</script>`}
	{@html `<script type="application/ld+json">${faqJsonLd(HOMEPAGE_FAQS)}</script>`}
	{@html `<script type="application/ld+json">${breadcrumbJsonLd([{ name: 'Home', url: 'https://bitcoinweighin.com/' }])}</script>`}
</svelte:head>

<div class="min-h-screen bg-zinc-950 text-zinc-100">
	<!-- Compact pinned bar — slides in once user has scrolled past the full controls. -->
	<div class="sticky-bar" class:visible={showStickyBar} aria-hidden={!showStickyBar}>
		<div class="mx-auto flex h-11 max-w-2xl items-center gap-3 px-4">
			<span class="min-w-[3.25rem] whitespace-nowrap font-mono text-xs text-amber-400">
				{sliderMode === 'btc' ? formatBtc(sceneBtc) : formatBtc(lockedBtcForDateMode)}
			</span>
			<div
				class="slider-wrap slider-wrap--below flex-1 min-w-0"
				data-tooltip={sliderMode === 'btc' ? 'double-click to lock BTC amount and change date' : 'double-click to lock date and change BTC amount'}
			>
				<input
					type="range"
					min="0"
					max={SLIDER_STEPS}
					value={sliderPos}
					oninput={handleSliderInput}
					ondblclick={handleSliderDblClick}
					onkeydown={handleSliderKeydown}
					class="w-full"
					class:accent-amber-500={sliderMode === 'btc'}
					class:accent-sky-400={sliderMode === 'date'}
					aria-label={sliderMode === 'btc' ? 'BTC amount' : 'Date'}
					tabindex={showStickyBar ? 0 : -1}
				/>
			</div>
			{#if sliderMode === 'btc'}
				{#if dayPrices}
					<span class="min-w-[4.5rem] whitespace-nowrap text-right font-mono text-xs text-zinc-200">
						{formatUsd(sceneBtc * dayPrices.btc)}
					</span>
				{/if}
			{:else}
				<span class="min-w-[4.5rem] whitespace-nowrap text-right font-mono text-xs text-zinc-200">
					{formatDateReadout($selectedDate)}
				</span>
			{/if}
		</div>
	</div>

	<!--
		Header: two-zone layout. Brand left (image + subtitle), preset pills
		right. The subscribe form lives in its own visible section after the
		Hashweight panel (see .subscribe-section below) — not in the header.
	-->
	<div class="mx-auto max-w-[1280px] px-6 pt-4 sm:pt-6">
		<header class="site-header">
			<a href="/" class="brand" aria-label="Bitcoin Weigh-In home">
				<picture>
					<source
						srcset="/header@1x.webp 1x, /header.webp 2x"
						type="image/webp"
					/>
					<img
						src="/header.jpg"
						alt="Bitcoin Weigh-In"
						width="960"
						height="340"
						fetchpriority="high"
						decoding="async"
						class="brand__mark"
					/>
				</picture>
				<h1 class="brand__h1">
					Bitcoin's purchasing power in physical commodities
				</h1>
				<p class="brand__subtitle">
					How much gold, silver, cash or plutonium does 1 BTC buy? Live ratios, daily, since 2013.
				</p>
			</a>
			<div class="header-pills">
				<PresetBar activePresetId={$activePreset} onSelect={handlePresetSelect} />
			</div>
		</header>
	</div>

	<!-- Hero: one live WebGL stage + Au/Ag/Pu tabs + slider + readout (one-stage layout, pre-launch review §2) -->
	<div class="mx-auto mt-8 max-w-2xl md:max-w-[1100px] px-4 pb-6 sm:pb-10">
		<HeroStage
			bind:this={heroStageEl}
			commodities={HERO_COMMODITIES}
			bind:selectedId={selectedCommodity}
			amounts={heroAmounts}
			btcAmount={sceneBtc}
			btcUsdPrice={dayPrices?.btc ?? 0}
			{prices}
			selectedDate={$selectedDate}
		>
			{#snippet controls()}
			<!-- Controls — two-row compact panel (~120px tall) -->
			<div class="controls-panel">
				<div class="controls-slider">
					<div class="slider-row">
						{#if sliderMode === 'date' && !reduceMotion}
							<!--
								Play button (brief \u00a71.4a) \u2014 date mode only, hidden entirely
								under reduced motion (not just disabled). Space bar is the
								keyboard equivalent (handleGlobalKeydown), gated the same way.
							-->
							<button
								type="button"
								class="play-btn"
								onclick={togglePlayback}
								disabled={sortedDates.length < 2}
								aria-label={playing ? 'Pause date playback' : 'Play \u2014 sweep through history to today'}
								aria-pressed={playing}
								title={playing ? 'Pause (space)' : 'Play (space) \u2014 sweep to the latest date'}
							>
								{playing ? '\u23f8' : '\u25b6'}
							</button>
						{/if}
						<div
							class="slider-wrap flex-1 min-w-0"
							data-tooltip={sliderMode === 'btc' ? 'double-click to lock BTC amount and change date' : 'double-click to lock date and change BTC amount'}
						>
							<input
								type="range"
								min="0"
								max={SLIDER_STEPS}
								value={sliderPos}
								oninput={handleSliderInput}
								ondblclick={handleSliderDblClick}
								onkeydown={handleSliderKeydown}
								class="slider"
								class:accent-amber-500={sliderMode === 'btc'}
								class:accent-sky-400={sliderMode === 'date'}
								aria-label={sliderMode === 'btc' ? 'BTC amount' : 'Date'}
							/>
							<!--
								Milestone dots (brief \u00a71.4c) \u2014 dataset-derived crossing
								points, date mode only. Purely decorative marks over the
								track; the caption below carries the information.
							-->
							{#if sliderMode === 'date'}
								{#each milestoneMarks as m (m.date + m.commodity)}
									<div class="milestone-dot" style="left: {m.pct}%" aria-hidden="true"></div>
								{/each}
							{/if}
						</div>
					</div>
					<div class="slider-range">
						{#if sliderMode === 'btc'}
							<span>1 sat</span>
							<span>21M</span>
						{:else}
							<span>{firstDate ? firstDate.slice(0, 4) : ''}</span>
							<span>Today</span>
						{/if}
					</div>
					{#if sliderMode === 'date'}
						<!--
							Milestone caption slot (brief \u00a71.4c) \u2014 fixed-height so a
							crossing's label appearing/fading never shifts layout, same
							treatment as the Daily Delta line in HeroStage.svelte.
						-->
						<p
							class="milestone-caption"
							class:milestone-caption--visible={!!milestoneCaption}
							aria-live="polite"
						>
							{milestoneCaption?.label ?? ''}
						</p>
					{/if}
				</div>

				<div class="controls-value-row">
					<div class="value-block">
						{#if sliderMode === 'btc'}
							{#if editingAmount}
								<!--
									Click-to-type (brief §1.5a): same box, same type — the input
									is styled identical to the readout so toggling never shifts
									layout. Accepts BTC ("0.5"), sats ("50000 sats", "10k sats"),
									and dollars ("$1M") via the day's price. Invalid input just
									reverts — no error state.
								-->
								<input
									bind:this={amountInputEl}
									bind:value={amountDraft}
									onkeydown={handleAmountKeydown}
									onblur={commitAmountEdit}
									class="value-btc value-btc--input"
									type="text"
									inputmode="decimal"
									spellcheck="false"
									autocomplete="off"
									aria-label="Type a BTC amount, sats amount, or dollar amount"
									placeholder="0.5 · 50k sats · $1M"
								/>
							{:else}
								<button
									type="button"
									class="value-btc value-btc--button"
									onclick={startAmountEdit}
									title="Click to type an amount — BTC, sats, or $"
								>
									{formatBtc(sceneBtc)}
								</button>
							{/if}
							{#if dayPrices}
								<div class="value-context">
									{formatUsd(sceneBtc * dayPrices.btc)} · {formatDateReadout($selectedDate)}
								</div>
							{/if}
						{:else}
							<div class="value-btc">{formatDateReadout($selectedDate)}</div>
							{#if dayPrices}
								<div class="value-context">
									{formatBtc(lockedBtcForDateMode)} locked · {formatUsd(lockedBtcForDateMode * dayPrices.btc)}
								</div>
							{:else}
								<div class="value-context">{formatBtc(lockedBtcForDateMode)} locked</div>
							{/if}
						{/if}
					</div>
					<!--
						Visible BTC | DATE mode toggle (brief §1.5c) — the dblclick
						shortcut stays (tooltip unchanged); this makes the second mode
						discoverable without hover. Disabled until the archive loads,
						same guard as setSliderMode. Colour-coding matches the slider:
						amber = BTC, sky = date.
					-->
					<div class="mode-toggle" role="group" aria-label="Slider mode">
						<button
							type="button"
							class="mode-toggle__seg mode-toggle__seg--btc"
							class:mode-toggle__seg--active={sliderMode === 'btc'}
							aria-pressed={sliderMode === 'btc'}
							onclick={() => setSliderMode('btc')}
						>
							BTC
						</button>
						<button
							type="button"
							class="mode-toggle__seg mode-toggle__seg--date"
							class:mode-toggle__seg--active={sliderMode === 'date'}
							aria-pressed={sliderMode === 'date'}
							disabled={sortedDates.length <= 1}
							onclick={() => setSliderMode('date')}
						>
							DATE
						</button>
					</div>
				</div>
			</div>

			<!--
				Sentinel: sits just below the controls card. When it scrolls above
				the viewport the pinned compact bar slides in. The IO entry's
				boundingClientRect.top < 0 means "above" rather than "below" — so
				we distinguish "scrolled past" from "not yet reached".
			-->
			<!--
				Sentinel: sits just below the controls card. When it scrolls above
				the viewport the pinned compact bar slides in.
			-->
			<div bind:this={sentinelEl} aria-hidden="true" class="h-px"></div>
			{/snippet}
		</HeroStage>

		<!-- Hashweight panel — unchanged. -->
		<div class="mt-12">
			<NetworkWeightPanel />
		</div>

		<!--
			Subscribe — The Weigh-In. The Beehiiv inline form renders INSIDE
			.subscribe-slot (the v3 loader places inline forms at the embed
			script's DOM position; see the $effect above). min-height reserves
			space so the async form doesn't shift layout when it lands.
		-->
		<section aria-labelledby="subscribe-heading" class="subscribe-section mt-12">
			<h2 id="subscribe-heading" class="subscribe-heading">The Weigh-In — the newsletter</h2>
			<p class="subscribe-sub">What a bitcoin weighs, and what moved it. Same voice as the site.</p>
			<div bind:this={subscribeSlotEl} class="subscribe-slot">
				<noscript><p class="subscribe-sub">The subscribe form needs JavaScript.</p></noscript>
			</div>
		</section>
	</div>

		<!--
			SEO + AI-bot surface. The visible copy intentionally mirrors the
			FAQPage JSON-LD verbatim — Google penalises FAQ structured data
			whose answers aren't visible on the page. Keep this block
			crawlable (no hidden display, no JS gate) and edit copy via
			$lib/seo/faqs.ts so the JSON-LD stays in lockstep.
		-->
		<section aria-labelledby="about-heading" class="seo-section">
			<div class="mx-auto max-w-3xl px-4 py-12 sm:py-16">
				<h2 id="about-heading" class="seo-section__h2">
					Bitcoin in things you can hold
				</h2>
				<p class="seo-section__p">
					<strong>Bitcoin Weigh-In</strong> answers a question that's harder than it looks: what
					does <em>one bitcoin</em> actually buy, expressed as something you could pick up off a
					table? The site renders a single BTC's purchasing power as physical commodities —
					gold, silver, plutonium-238, cocaine — at <em>true relative scale</em>, next to a
					constant 9-kg Shiba Inu named Sat so the eye has somewhere to land. Move the slider and the cube
					grows or shrinks; scrub the date and you can watch a bitcoin's weight in gold drift
					across thirteen years of market history.
				</p>
				<p class="seo-section__p">
					Under the hood is a public, daily-updated dataset of commodity prices in BTC going
					back to 2 January 2013, sourced from CoinGecko, GoldAPI.io and FRED with deterministic
					BTC supply computed from the protocol's halving schedule. The
					<a href="/data" class="seo-link">dataset is CC-BY-4.0</a> and ships as CSV, JSON,
					NDJSON and Parquet — useful if you're doing your own bitcoin-vs-commodities analysis.
					The <a href="/methodology" class="seo-link">methodology page</a> documents every
					source, every forward-fill rule, and the cross-validation pipeline that flags
					provider disagreements above 0.5%.
				</p>

				<h2 class="seo-section__h2">Per-commodity deep-dives</h2>
				<p class="seo-section__p">
					Each launch commodity has its own page with the live ratio, market context,
					and FAQ:
				</p>
				<ul class="seo-cards">
					<li>
						<a href="/btc/gold" class="seo-card">
							<span class="seo-card__title">BTC → Gold</span>
							<span class="seo-card__sub">How much gold does 1 BTC buy?</span>
						</a>
					</li>
					<li>
						<a href="/btc/silver" class="seo-card">
							<span class="seo-card__title">BTC → Silver</span>
							<span class="seo-card__sub">Troy ounces of silver per bitcoin.</span>
						</a>
					</li>
					<li>
						<a href="/btc/pu238" class="seo-card">
							<span class="seo-card__title">BTC → Plutonium-238</span>
							<span class="seo-card__sub">The radioisotope that powers spacecraft.</span>
						</a>
					</li>
					<li>
						<a href="/btc/cocaine" class="seo-card">
							<span class="seo-card__title">BTC → Cocaine</span>
							<span class="seo-card__sub">Wholesale, producer, retail tiers.</span>
						</a>
					</li>
					<li>
						<a href="/btc/cash" class="seo-card">
							<span class="seo-card__title">BTC → Cash</span>
							<span class="seo-card__sub">A literal stack of $1 bills, to true thickness.</span>
						</a>
					</li>
				</ul>

				<h2 class="seo-section__h2">Free, citable, machine-readable</h2>
				<p class="seo-section__p">
					The full daily archive (BTC, gold, silver, platinum, copper, Brent crude,
					wheat, coffee — 2013-present) is published under
					<a
						href="https://creativecommons.org/licenses/by/4.0/"
						class="seo-link">Creative Commons CC-BY-4.0</a
					>
					at <a href="/data" class="seo-link">/data</a> in CSV, JSON, NDJSON, and
					Parquet. Cite as <em>Bitcoin Weigh-In Daily Commodity Price Dataset</em>;
					attribution is the only restriction. The
					<a href="/methodology" class="seo-link">methodology page</a> documents every
					source, every forward-fill rule, and the cross-validation pipeline. Browse
					historical purchasing power year-by-year at
					<a href="/snapshot" class="seo-link">/snapshot</a>.
				</p>

				<h2 class="seo-section__h2">Frequently asked questions</h2>
				<dl class="seo-faq">
					{#each HOMEPAGE_FAQS as faq (faq.question)}
						<dt class="seo-faq__q">{faq.question}</dt>
						<dd class="seo-faq__a">{faq.answer}</dd>
					{/each}
				</dl>
			</div>
		</section>
</div>

<style>
	/* ── Subscribe section ─────────────────────────── */
	.subscribe-section {
		background: #09090b;
		border-radius: 12px;
		padding: 24px;
	}
	.subscribe-heading {
		font-family: 'Inter Tight', 'Inter', sans-serif;
		font-size: 22px;
		font-weight: 600;
		color: #f4f4f5;
		margin: 0 0 6px 0;
		letter-spacing: -0.02em;
	}
	.subscribe-sub {
		font-size: 14px;
		color: #71717a;
		margin: 0 0 16px 0;
		line-height: 1.5;
		max-width: 540px;
	}
	.subscribe-slot {
		/* Reserve roughly one slim inline form's height; grows when it lands. */
		min-height: 96px;
	}

	.controls-panel {
		background: #18181b; /* zinc-900 */
		border-radius: 8px;
		padding: 14px 16px;
		display: flex;
		flex-direction: column;
		gap: 10px;
	}
	.controls-slider {
		display: flex;
		flex-direction: column;
		gap: 4px;
	}
	/* Play button (brief §1.4a) sits to the left of the slider in date mode.
	   Row is a plain flex wrapper — with the button absent (btc mode, or
	   reduced motion) it holds just the slider-wrap and lays out identically
	   to the old unwrapped markup. */
	.slider-row {
		display: flex;
		align-items: center;
		gap: 8px;
	}
	.play-btn {
		flex-shrink: 0;
		width: 28px;
		height: 28px;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		border: 1px solid #3f3f46; /* zinc-700 */
		border-radius: 6px;
		background: #18181b; /* zinc-900 */
		color: #38bdf8; /* sky-400 — matches the date-mode slider accent */
		font-size: 12px;
		line-height: 1;
		cursor: pointer;
		transition: background-color 120ms ease-out, border-color 120ms ease-out;
	}
	.play-btn:hover:not(:disabled) {
		background: rgba(56, 189, 248, 0.14);
		border-color: #38bdf8;
	}
	.play-btn:disabled {
		opacity: 0.4;
		cursor: default;
	}
	.play-btn:focus-visible {
		outline: 2px solid #38bdf8;
		outline-offset: 2px;
	}
	.slider-wrap {
		position: relative;
		width: 100%;
	}
	/* Milestone dots (brief §1.4c) — small, quiet marks over the track at
	   each dataset-derived crossing. Purely decorative (aria-hidden); the
	   caption below the slider carries the information for assistive tech. */
	.milestone-dot {
		position: absolute;
		top: 50%;
		width: 4px;
		height: 4px;
		border-radius: 50%;
		background: #52525b; /* zinc-600 */
		transform: translate(-50%, -50%);
		pointer-events: none;
	}
	/* Milestone crossing caption (brief §1.4c) — reserved min-height so its
	   appearance/fade never shifts layout, same treatment as HeroStage's
	   .delta-line. Transient-on-crossing (documented at milestoneCaption's
	   declaration): fades in/out over ~300ms, visible for ~2.5s total. Under
	   reduced motion the transition is removed — it just appears/disappears. */
	.milestone-caption {
		margin: 0;
		min-height: 16px;
		font-family: 'Inter Tight', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
		font-size: 12px;
		line-height: 1.4;
		color: #71717a; /* zinc-500 — matches the Daily Delta line's quiet register */
		letter-spacing: 0.005em;
		opacity: 0;
		transition: opacity 300ms ease;
	}
	.milestone-caption--visible {
		opacity: 1;
	}
	@media (prefers-reduced-motion: reduce) {
		.milestone-caption {
			transition: none;
		}
	}
	.slider-wrap::after {
		content: attr(data-tooltip);
		position: absolute;
		bottom: calc(100% + 6px);
		left: 50%;
		transform: translateX(-50%) translateY(4px);
		background: #27272a; /* zinc-800 */
		color: #a1a1aa;
		font-family: 'JetBrains Mono', 'SF Mono', 'Fira Code', ui-monospace, monospace;
		font-size: 11px;
		padding: 4px 8px;
		border-radius: 4px;
		white-space: nowrap;
		pointer-events: none;
		opacity: 0;
		transition: opacity 150ms ease, transform 150ms ease;
		border: 1px solid #3f3f46; /* zinc-700 */
		z-index: 10;
	}
	.slider-wrap:hover::after {
		opacity: 1;
		transform: translateX(-50%) translateY(0);
	}
	.slider-wrap--below::after {
		bottom: auto;
		top: calc(100% + 6px);
		transform: translateX(-50%) translateY(-4px);
	}
	.slider-wrap--below:hover::after {
		transform: translateX(-50%) translateY(0);
	}
	.slider {
		width: 100%;
	}
	.slider-range {
		display: flex;
		justify-content: space-between;
		font-family: 'JetBrains Mono', 'SF Mono', 'Fira Code', ui-monospace, monospace;
		font-size: 11px;
		color: #71717a; /* zinc-500 */
	}
	.controls-value-row {
		display: flex;
		align-items: flex-end;
		justify-content: space-between;
		gap: 16px;
	}
	.value-block {
		display: flex;
		flex-direction: column;
		gap: 2px;
		min-width: 0;
	}
	.value-btc {
		font-family: 'JetBrains Mono', 'SF Mono', 'Fira Code', ui-monospace, monospace;
		font-variant-numeric: tabular-nums;
		font-size: 22px;
		font-weight: 600;
		line-height: 1.15;
		color: #f5f0e6;
		letter-spacing: -0.01em;
	}
	/* Click-to-type: the button (rest state) and the input (edit state) must
	   occupy the identical box as the plain readout — no layout shift when
	   toggling. Both inherit .value-btc's type; everything below just strips
	   native chrome. */
	.value-btc--button {
		background: none;
		border: none;
		padding: 0;
		margin: 0;
		text-align: left;
		cursor: text;
		border-bottom: 1px dashed transparent;
	}
	.value-btc--button:hover {
		border-bottom-color: #3f3f46; /* zinc-700 — quiet "this is editable" affordance */
	}
	.value-btc--input {
		background: none;
		border: none;
		padding: 0;
		margin: 0;
		width: 100%;
		min-width: 0;
		outline: none;
		caret-color: #f59e0b; /* amber-500, matches the slider thumb */
	}
	.value-btc--input::placeholder {
		color: #3f3f46;
		font-weight: 400;
	}
	.value-context {
		font-family: 'JetBrains Mono', 'SF Mono', 'Fira Code', ui-monospace, monospace;
		font-variant-numeric: tabular-nums;
		font-size: 14px;
		color: #9aa0a6;
	}
	/* BTC | DATE segmented mode toggle — replaces the passive DATE badge.
	   Active segment takes the mode's slider colour (amber / sky). */
	.mode-toggle {
		flex-shrink: 0;
		align-self: flex-end;
		display: inline-flex;
		border: 1px solid #3f3f46; /* zinc-700 */
		border-radius: 6px;
		overflow: hidden;
	}
	.mode-toggle__seg {
		font-family: 'JetBrains Mono', 'SF Mono', 'Fira Code', ui-monospace, monospace;
		font-size: 10px;
		font-weight: 700;
		letter-spacing: 0.08em;
		color: #71717a; /* zinc-500 */
		background: #18181b; /* zinc-900 */
		border: none;
		padding: 5px 9px;
		cursor: pointer;
		transition: background-color 120ms ease-out, color 120ms ease-out;
	}
	.mode-toggle__seg + .mode-toggle__seg {
		border-left: 1px solid #3f3f46;
	}
	.mode-toggle__seg:hover:not(:disabled):not(.mode-toggle__seg--active) {
		color: #a1a1aa;
	}
	.mode-toggle__seg:disabled {
		opacity: 0.4;
		cursor: default;
	}
	.mode-toggle__seg--active.mode-toggle__seg--btc {
		background: rgba(245, 158, 11, 0.14); /* amber */
		color: #f59e0b;
	}
	.mode-toggle__seg--active.mode-toggle__seg--date {
		background: rgba(56, 189, 248, 0.14); /* sky */
		color: #38bdf8;
	}

	.site-header {
		display: flex;
		flex-direction: column;
		gap: 16px;
		padding-bottom: 0;
	}
	.brand {
		display: flex;
		flex-direction: column;
		gap: 6px;
		flex-shrink: 0;
		text-decoration: none;
		color: inherit;
	}
	.brand__mark {
		display: block;
		height: 80px;
		width: auto;
		max-width: 100%;
	}
	.brand__h1 {
		margin: 4px 0 0;
		font-size: 17px;
		font-weight: 600;
		line-height: 1.25;
		color: #f5f0e6;
		letter-spacing: -0.005em;
		text-wrap: balance;
	}
	@media (min-width: 768px) {
		.brand__h1 {
			font-size: 18px;
		}
	}
	.brand__subtitle {
		margin: 0;
		color: #71717a; /* zinc-500 — slightly more recessive */
		font-size: 13px;
		font-weight: 400;
		line-height: 1.4;
		text-wrap: balance;
	}
	.seo-section {
		border-top: 1px solid #27272a; /* zinc-800 */
		background: #09090b; /* zinc-950 */
	}
	.seo-section__h2 {
		font-size: 1.25rem;
		font-weight: 600;
		color: #f5f0e6;
		margin: 2rem 0 0.75rem;
		letter-spacing: -0.01em;
		text-wrap: balance;
	}
	.seo-section__h2:first-of-type {
		margin-top: 0;
	}
	.seo-section__p {
		font-size: 0.9375rem;
		line-height: 1.65;
		color: #a1a1aa; /* zinc-400 */
		margin: 0.6rem 0;
	}
	.seo-section__p strong {
		color: #e4e4e7; /* zinc-200 */
		font-weight: 600;
	}
	.seo-link {
		color: #f5f0e6;
		text-decoration: underline;
		text-decoration-color: #71717a;
		text-underline-offset: 2px;
	}
	.seo-link:hover {
		text-decoration-color: #f5f0e6;
	}
	.seo-cards {
		list-style: none;
		display: grid;
		grid-template-columns: 1fr;
		gap: 0.6rem;
		margin: 0.5rem 0 0;
		padding: 0;
	}
	@media (min-width: 640px) {
		.seo-cards {
			grid-template-columns: 1fr 1fr;
		}
	}
	.seo-card {
		display: block;
		padding: 0.85rem 1rem;
		border: 1px solid #27272a; /* zinc-800 */
		border-radius: 6px;
		text-decoration: none;
		transition: border-color 150ms ease, background 150ms ease;
		background: #18181b; /* zinc-900 */
	}
	.seo-card:hover {
		border-color: #a16207; /* amber-700 */
		background: #1c1917;
	}
	.seo-card__title {
		display: block;
		color: #f5f0e6;
		font-weight: 600;
		font-size: 0.9375rem;
	}
	.seo-card__sub {
		display: block;
		margin-top: 0.15rem;
		color: #a1a1aa;
		font-size: 0.85rem;
	}
	.seo-faq {
		margin: 0.5rem 0 0;
	}
	.seo-faq__q {
		font-size: 0.9375rem;
		font-weight: 600;
		color: #e4e4e7;
		margin-top: 1.25rem;
		text-wrap: balance;
	}
	.seo-faq__a {
		margin: 0.35rem 0 0;
		font-size: 0.9rem;
		line-height: 1.6;
		color: #a1a1aa;
	}
	.header-pills {
		width: 100%;
	}

	@media (min-width: 768px) {
		.site-header {
			flex-direction: row;
			align-items: flex-start;
			gap: 28px;
		}
		.brand {
			/* Tighter brand column so pills have comfortable room to wrap */
			flex: 0 0 260px;
		}
		.header-pills {
			flex: 1 1 0;
			min-width: 0;
			/* Align pill rows' top with the logo top */
			padding-top: 0;
		}
	}
	@media (min-width: 1280px) {
		.brand {
			flex: 0 0 300px;
		}
	}

	.sticky-bar {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		z-index: 50;
		background: rgba(9, 9, 11, 0.92); /* zinc-950 @ 92% */
		backdrop-filter: blur(8px);
		-webkit-backdrop-filter: blur(8px);
		border-bottom: 1px solid #27272a; /* zinc-800 */
		transform: translateY(-100%);
		opacity: 0;
		transition:
			transform 200ms ease-out,
			opacity 200ms ease-out;
		pointer-events: none;
	}
	.sticky-bar.visible {
		transform: translateY(0);
		opacity: 1;
		pointer-events: auto;
	}
	@media (prefers-reduced-motion: reduce) {
		.sticky-bar {
			transition: none;
		}
	}
</style>
