/**
 * build-cube-modes.ts — compute the ring of each cube material, once.
 *
 *   npx tsx scripts/build-cube-modes.ts
 *
 * Writes src/lib/scene/cube-modes.json: for each material, the cube's
 * free-vibration modes as DIMENSIONLESS frequencies Ω = f·L / c_t (L = edge,
 * c_t = shear wave speed) with a relative loudness for a landing on one face.
 * Everything about the sound that depends on size is then a single scale
 * factor at runtime (f = Ω · c_t / L), which is why it can ship as a table.
 *
 * The modes depend only on Poisson's ratio; the loudness weights also
 * depend on c_t / c_l, through the contact time of a flat landing. Both come
 * from the material constants in src/lib/scene/acoustics.ts, so the
 * table and the runtime can never disagree about the material.
 *
 * Method and validation: src/lib/scene/modal.ts, tests/scene-modal.test.ts.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { solveBox, landingCoupling, halfSineSpectrum } from '../src/lib/scene/modal.js';
import { MATERIAL_ACOUSTICS, LANDING_TILT, poissonOf } from '../src/lib/scene/acoustics.js';

const ORDER = 10; // Legendre degree; lowest modes converged to < 0.5% (tests)
const OMEGA_MAX = 4; // keep modes up to Ω = 4 (≈ 3× the contact-spectrum knee)
const WEIGHT_FLOOR = 2e-3; // drop modes below −54 dB of the loudest

const out: Record<string, { poisson: number; modes: [number, number][] }> = {};

for (const [id, mat] of Object.entries(MATERIAL_ACOUSTICS)) {
	const nu = poissonOf(mat);
	const model = solveBox([1, 1, 1], nu, ORDER);
	// Contact time of a flat landing, τ = 2L / c_l, in units of L / c_t:
	// f·τ = Ω · 2 c_t / c_l.
	const ftPerOmega = (2 * mat.ct) / mat.cl;

	// Merge degenerate modes (cubic symmetry) by summing energy.
	const groups: { omega: number; e: number }[] = [];
	for (const mode of model.modes) {
		if (mode.omega < 1e-6) continue; // rigid-body
		const omega = mode.omega / Math.PI;
		if (omega > OMEGA_MAX) break;
		const { force, surface } = landingCoupling(model, mode, LANDING_TILT);
		const amp = Math.abs(force) * surface * halfSineSpectrum(omega * ftPerOmega);
		const last = groups[groups.length - 1];
		if (last && Math.abs(last.omega - omega) < 1e-6 * omega) last.e += amp * amp;
		else groups.push({ omega, e: amp * amp });
	}
	const peak = Math.max(...groups.map((g) => Math.sqrt(g.e)));
	const modes = groups
		.map((g) => [Number(g.omega.toPrecision(6)), Number((Math.sqrt(g.e) / peak).toPrecision(4))] as [number, number])
		.filter(([, w]) => w >= WEIGHT_FLOOR);
	out[id] = { poisson: Number(nu.toFixed(4)), modes };
	console.log(`${id}: ν=${nu.toFixed(4)}  ${modes.length} modes  lowest Ω=${modes[0][0]}  loudest Ω=${modes.find(([, w]) => w === 1)?.[0]}`);
}

const file = resolve('src/lib/scene/cube-modes.json');
writeFileSync(
	file,
	JSON.stringify(
		{
			_about:
				'Generated by scripts/build-cube-modes.ts — do not edit. Free-vibration modes of an elastic cube (Rayleigh–Ritz, Legendre order ' +
				ORDER +
				'), as [Ω, weight] with Ω = f·L/c_t and weight = relative sound-pressure amplitude after a flat landing (degenerate modes merged).',
			...out,
		},
		null,
		'\t'
	) + '\n'
);
console.log(`wrote ${file}`);
